### ISSUE TITLE
draft method signature for flagging

### ISSUE THREAD

**Issue by yupinghuang** [Radio-Camera-Initiative/r3_central_manager#32]
I'm passing in `buffer_ptr` and hoping that it's the right thing

```
// Taking buffer_ptr because these things need to match. How do we guarantee that when we pop?
// is there a way for me to identify the first three as input and the last thing as output?
// Also should I pass these things by reference?
void flag_data(buffer_ptr<std::complex> vis_bp, buffer_ptr<float> uvw_bp, buffer_ptr<int> baselines, buffer_ptr<bool> flags_bp) {
    std::vector s = vis.bp->shape;
    int n_timesteps = s(0);
    int n_bl = s(1);
    int n_chan = s(2);
    int n_corr = s(3);
    // uvw should have shape (n_timesteps, n_bl, 3)
    // baselines should have shape (n_timesteps, b_bl, 2) corresponding to antenna indices
    // flags_bp should have shape (n_timesteps, n_bl, n_chan, n_corr
   // TODO as a first step fill flags_bp with False
}
```
let me know what's wrong about this.

**Comment by mlaures** [comment]
Currently the types used in the gridding.cpp for the uvw and baselines are different. It would be:
buffer_ptr<idg::UVW<float>> uvw_bp
buffer_ptr<std::pair<unsigned int, unsigned int>> baselines

Do we want to simply the types for the recyclers or change the flagging signature?

**Comment by yupinghuang** [comment]
idg::UVW is an Array2D<float>. We should stick to templatizing with primitives? If we do `buffer_ptr<idg::UVW> uvw_bp` and then `uvw_bp.get()` you get a pointer to the `idg::UVW` object which makes no guarantee that it's gonna be the start of the underlying array thing

**Comment by mlaures** [comment]
Alright I can definitely change the recycler to take primitives instead of the idg::UVW. I don't know if std::pair will give the same problems as the idg object (I assume not but that may be premature).

Also I notice the shape of the uvw is different in this flagging version: (n_timesteps, n_bl, 3)

In the original MS reading code, the uvw is:
  idg::Array2D<idg::UVW<float>> uvw =
      proxy.allocate_array2d<idg::UVW<float>>(meta.nr_baselines, meta.nr_timesteps);

Considering timesteps should be 1, it may not matter but I don't know if flagging will indeed need more than one timestep

**Comment by mlaures** [comment]
Ah so I've looking into the idg::UVW typedef and it is actually a struct of three floats - considering this, I think it's fine to use idg::UVW but it's your call.
